apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-db-sts
spec:
  selector:
    matchLabels:
      app: mern-db
  template:
    metadata:
      labels:
        app: mern-db
    spec:
      containers:
      - name: mern-db-con
        image: mongo:latest
        resources:
          requests:
            memory: 150Mi
            cpu: 250m
          limits:
            memory: 250Mi
            cpu: 500m
        ports:
          - containerPort: 27017

--- 
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mern-db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP


